spring.application.name=BaristaJob2026
## MySQL connectie
## vervang schemaName door de naam van je schema in MySQL (
spring.datasource.url=jdbc:mysql://localhost:3306/schemaName?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
# vul in met je MySQL localinstance gebruikersnaam en wachtwoord
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# hibernate instelling
spring.jpa.hibernate.ddl-auto=create-drop

# moet op dev blijven om seeding te kunnen runnen
spring.profiles.active=dev

# properties locatie
spring.messages.basename=i18n/messages

